#!/bin/bash
# Generate database credential secrets for Automation Orchestrator
# Usage: ./generate-secrets.sh [overlay-name]
#   overlay-name: default | with-postgres (default: default)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Default overlay
OVERLAY="${1:-default}"
SECRETS_DIR="$PROJECT_ROOT/instance/overlays/$OVERLAY/secrets"
TEMPLATE_DIR="$PROJECT_ROOT/instance/base/secrets"

# Check if overlay exists
if [ ! -d "$PROJECT_ROOT/instance/overlays/$OVERLAY" ]; then
    echo "Error: Overlay '$OVERLAY' does not exist"
    echo "Available overlays: default, with-postgres"
    exit 1
fi

# Create secrets directory if it doesn't exist
mkdir -p "$SECRETS_DIR"

echo "==================================="
echo "Automation Orchestrator Secret Generator"
echo "==================================="
echo "Overlay: $OVERLAY"
echo "Output: $SECRETS_DIR"
echo ""

# Function to generate a secure password
generate_password() {
    openssl rand -base64 32 | tr -d "=+/" | cut -c1-32
}

# Get PostgreSQL connection details
echo "PostgreSQL Connection Details"
echo "-----------------------------"
read -p "PostgreSQL host [postgresql.automation-orchestrator.svc.cluster.local]: " PG_HOST
PG_HOST=${PG_HOST:-postgresql.automation-orchestrator.svc.cluster.local}

read -p "PostgreSQL port [5432]: " PG_PORT
PG_PORT=${PG_PORT:-5432}

read -p "PostgreSQL SSL mode [prefer]: " PG_SSLMODE
PG_SSLMODE=${PG_SSLMODE:-prefer}

echo ""
echo "Generating secure passwords..."
ORCHESTRATOR_PASSWORD=$(generate_password)
TEMPORAL_PASSWORD=$(generate_password)

# Generate orchestrator-pg-credentials secret
echo "Creating orchestrator-pg-credentials secret..."
cat > "$SECRETS_DIR/orchestrator-pg-credentials.yaml" <<EOF
---
# Generated by generate-secrets.sh on $(date)
# DO NOT COMMIT THIS FILE TO VERSION CONTROL
apiVersion: v1
kind: Secret
metadata:
  name: orchestrator-pg-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  host: "$PG_HOST"
  port: "$PG_PORT"
  database: "orchestrator"
  username: "orchestrator"
  password: "$ORCHESTRATOR_PASSWORD"
  sslmode: "$PG_SSLMODE"
EOF

# Generate temporal-pg-credentials secret
echo "Creating temporal-pg-credentials secret..."
cat > "$SECRETS_DIR/temporal-pg-credentials.yaml" <<EOF
---
# Generated by generate-secrets.sh on $(date)
# DO NOT COMMIT THIS FILE TO VERSION CONTROL
apiVersion: v1
kind: Secret
metadata:
  name: temporal-pg-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  host: "$PG_HOST"
  port: "$PG_PORT"
  database: "temporal"
  username: "temporal"
  password: "$TEMPORAL_PASSWORD"
  sslmode: "$PG_SSLMODE"
EOF

echo ""
echo "✓ Secrets generated successfully!"
echo ""
echo "Generated passwords (save these securely):"
echo "  Orchestrator user: $ORCHESTRATOR_PASSWORD"
echo "  Temporal user:     $TEMPORAL_PASSWORD"
echo ""
echo "IMPORTANT: Update your PostgreSQL database with these passwords!"
echo ""
echo "If using the bundled PostgreSQL, update:"
echo "  postgresql/base/configmap-init.yaml"
echo "  Replace REPLACE_orchestrator_password with: $ORCHESTRATOR_PASSWORD"
echo "  Replace REPLACE_temporal_password with: $TEMPORAL_PASSWORD"
echo ""

# Ask about optional secrets
echo "Optional Secrets"
echo "----------------"
read -p "Generate optional secrets (JWT keys, encryption key, Redis)? [y/N]: " GENERATE_OPTIONAL

if [[ "$GENERATE_OPTIONAL" =~ ^[Yy]$ ]]; then
    echo ""
    echo "Generating optional secrets..."

    # JWT signing key (ES256 - ECDSA P-256)
    if command -v openssl &> /dev/null; then
        echo "Generating JWT primary signing key..."
        JWT_KEY_FILE="$SECRETS_DIR/jwt-primary-key.yaml"
        TEMP_KEY=$(mktemp)
        openssl ecparam -genkey -name prime256v1 -noout -out "$TEMP_KEY"
        JWT_KEY_BASE64=$(base64 < "$TEMP_KEY" | tr -d '\n')
        rm "$TEMP_KEY"

        cat > "$JWT_KEY_FILE" <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-primary-key
type: Opaque
data:
  jwt-primary.pem: $JWT_KEY_BASE64
EOF
        echo "✓ JWT primary key generated"
    fi

    # Encryption key for credentials
    ENCRYPTION_KEY=$(openssl rand -hex 32)
    cat > "$SECRETS_DIR/encryption-key.yaml" <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: credential-encryption-key
type: Opaque
stringData:
  secret-encryption-key: "$ENCRYPTION_KEY"
EOF
    echo "✓ Credential encryption key generated"

    # Redis password
    REDIS_PASSWORD=$(generate_password)
    cat > "$SECRETS_DIR/redis-password.yaml" <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-password
type: Opaque
stringData:
  password: "$REDIS_PASSWORD"
EOF
    echo "✓ Redis password generated"

    echo ""
    echo "Optional secrets created:"
    echo "  - JWT primary signing key"
    echo "  - Credential encryption key: $ENCRYPTION_KEY"
    echo "  - Redis password: $REDIS_PASSWORD"
fi

echo ""
echo "Next steps:"
echo "  1. Update PostgreSQL with the generated passwords (if using bundled PostgreSQL)"
echo "  2. Update instance/overlays/$OVERLAY/kustomization.yaml to reference the secrets"
echo "  3. Test the build: kustomize build instance/overlays/$OVERLAY"
echo ""
