---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automation-orchestrator

resources:
  - ../../base
  - namespace.yaml

patches:
  - target:
      kind: StatefulSet
      name: postgresql
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "1"
  - target:
      kind: Service
      name: postgresql
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "1"
  - target:
      kind: Job
      name: postgresql-init-databases
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "2"
