---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automation-orchestrator

resources:
  - ../../base
  - namespace.yaml

patches:
  - target:
      kind: OperatorGroup
      name: automation-orchestrator-operator
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "2"
      - op: replace
        path: /spec/targetNamespaces
        value:
          - automation-orchestrator
  - target:
      kind: Subscription
      name: automation-orchestrator-operator
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "2"
